#!/usr/bin/env bash

# shellcheck source=/dev/null
[[ $(source "/etc/os-release" 2>/dev/null; echo "$ID") == "clear-linux-os" ]] || exit 1

# CUDA uninstaller script for NVIDIA graphics on Clear Linux OS.
# Usage: sudo ./uninstall-cuda

if [[ -d "/opt/cuda" ]]; then

    # Note: /usr/local/cuda is a symbolic link to /opt/cuda
    echo "Uninstalling the NVIDIA CUDA Toolkit."
    rm -fr /usr/local/cuda /opt/cuda /etc/ld.so.conf.d/cuda-*.conf
    rm -f /etc/environment.d/10-nvidia-cuda.conf

    echo "Refreshing the dynamic linker run-time cache."
    ldconfig

    sync
fi

echo "Done"

