#!/usr/bin/env bash

# shellcheck source=/dev/null
[[ $(source "/etc/os-release" 2>/dev/null; echo "$ID") == "clear-linux-os" ]] || exit 1

echo "
Uninstaller script for NVIDIA driver on Clear Linux OS.
Usage: ./uninstall-driver

The uninstaller requires a non-graphical environment and privileged user i.e., sudo/root."
contflag=1 state=$(systemctl is-active graphical.target 2>&1)

if [[ "$state" == "active" ]]; then
    contflag=0
elif [[ -n $(pidof gnome-shell) || -n $(pidof xdg-desktop-portal) ]]; then
    contflag=0
fi

if [[ $contflag -eq 0 ]]; then
    echo "Reboot into multi-user mode to uninstall the driver."
    echo "Press the letter 'e' at the boot menu and prepend '3 '".
    exit 1  
fi


###############################################################################

# Reset configuration.
echo "Resetting configuration."
rm -f /etc/modprobe.d/nvidia-uvm.conf
rm -f /etc/ld.so.conf.d/nvidia.conf
rm -f /etc/kernel/cmdline.d/blacklist-nouveau.conf
rm -f /etc/kernel/cmdline.d/ignore-mod-sig.conf
rm -f /etc/kernel/cmdline.d/nvidia-drm.conf
rm -f /etc/kernel/cmdline.d/rcu.conf
rm -f /etc/kernel/cmdline-removal.d/intel-iommu.conf
rm -f /etc/swupd/config
rm -f /etc/systemd/system/fix-nvidia-libGL-trigger.service
rm -f /etc/systemd/system/update-triggers.target.wants/fix-nvidia-libGL-trigger.service
rm -f /etc/X11/xorg.conf.d/nvidia-files-opt.conf
rm -f /etc/X11/xorg.conf.d/nvidia-modules.conf

# remove configurations from older nvidia-driver-on-clear-linux installations
rm -f /etc/modprobe.d/disable-nouveau.conf
rm -f /etc/modprobe.d/nvidia-disable-nouveau.conf
rm -f /etc/modprobe.d/enable-nvidia-modeset.conf

echo "Reloading the systemd manager configuration."
systemctl daemon-reload

echo "Refreshing the dynamic linker run-time cache."
ldconfig

echo "Refreshing the boot configuration."
clr-boot-manager update

###############################################################################

# Support also, older nvidia-driver-on-clear-linux installations.

echo "Uninstalling the NVIDIA driver."
if [[ -x "/usr/bin/nvidia-uninstall" ]]; then
     /usr/bin/nvidia-uninstall --silent
elif [[ -x "/opt/nvidia/bin/nvidia-uninstall" ]]; then
     /opt/nvidia/bin/nvidia-uninstall --silent
fi

rm -fr /opt/nvidia

rm -f /etc/udev/rules.d/61-gdm.rules
rm -f /etc/X11/xorg.conf.d/nvidia-drm-outputclass.conf
rm -f /etc/X11/xorg.conf
rm -f /usr/lib32/libEGL.so
rm -f /usr/lib32/libGLESv1_CM.so
rm -f /usr/lib32/libGLESv2.so
rm -f /usr/lib32/libGL.so
rm -f /usr/lib32/libOpenCL.so
rm -f /usr/lib32/libOpenGL.so
rm -f /usr/lib64/libOpenCL.so
rm -f /usr/lib64/libnvidia-*
rm -f /usr/lib64/gbm/nvidia-drm_gbm.so
rm -f /var/log/nvidia-installer.log

sudo ldconfig

rm -f /usr/bin/nvidia-modprobe
rm -f /usr/local/bin/nvidia-settings
rm -f /usr/local/bin/nvidia-smi

echo "Repairing the lib-opengl bundle via swupd."
sudo swupd repair -x --bundles=lib-opengl --quiet | grep -v fixed

sync
echo "Please reboot the system."

